workspace: true

stages:
  - build
  - test

  jobs:
    # Prepare environment
    - name: build:prepare
      stage: build
      image: tqtrung09/ruby2.7.1:latest
      script:
        - bundle _2.1.4_ install --path vendor/bundle
      cache:
        - key: vendor_$CI_BRANCH
          paths:
          - vendor/bundle

    # Rspec => https://github.com/rspec/rspec-rails
    - name: test:rspec
      stage: test
      image: tqtrung09/ruby2.7.1:latest
      services:
        - image: mysql:5.7.32
          name: mysql
          environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=Aa@123456
            - MYSQL_DATABASE=sun_ci_cd_v4_rails6_sample_test
      before_script:
        - bundle _2.1.4_ install --path vendor/bundle
        - mkdir .sun-ci-reports
      script:
        - bundle _2.1.4_ exec rspec --format html --out .sun-ci-reports/rspec.html spec/
      artifacts:
        name: rspec_report
        paths:
          - .sun-ci-reports/rspec.html
        expires_in: 2 days

    # Bundle audit => https://github.com/rubysec/bundler-audit
    - name: test:bundle_audit
      stage: test
      image: tqtrung09/ruby2.7.1:latest
      before_script:
        - bundle _2.1.4_ install --path vendor/bundle
        - mkdir .sun-ci-reports
      script:
        - bundle _2.1.4_ exec bundle-audit check --update | tee .sun-ci-reports/bundle-audit.txt
      artifacts:
        name: bundle_audit_report
        paths:
          - .sun-ci-reports/bundle-audit.txt
        expires_in: 2 days

    # Brakeman => https://github.com/presidentbeef/brakeman
    - name: test:brakeman
      stage: test
      image: tqtrung09/ruby2.7.1:latest
      before_script:
        - bundle _2.1.4_ install --path vendor/bundle
        - mkdir .sun-ci-reports
      script:
        - bundle _2.1.4_ exec brakeman -o .sun-ci-reports/brakeman.html
      artifacts:
        name: brakeman_report
        paths:
          - .sun-ci-reports/brakeman.html
        expires_in: 2 days

    # Reek => https://github.com/troessner/reek
    - name: test:reek
      stage: test
      image: tqtrung09/ruby2.7.1:latest
      before_script:
        - bundle _2.1.4_ install --path vendor/bundle
        - mkdir .sun-ci-reports
      script:
        - bundle _2.1.4_ exec reek | tee .sun-ci-reports/reek.txt
      artifacts:
        name: bundle_audit_report
        paths:
          - .sun-ci-reports/reek.txt
        expires_in: 2 days
